2021-07-28 11:03:17,799 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 11:15:51,293 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 11:15:53,423 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 11:17:56,188 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 11:17:58,239 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 11:18:39,574 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 11:18:41,480 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 11:18:55,049 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 11:18:56,993 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 11:21:36,457 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 11:21:38,634 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 11:22:52,730 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 11:22:54,760 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 11:26:53,810 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 11:26:55,917 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 11:29:45,895 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 11:29:49,011 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 15:02:03,437 django.request WARNING  Not Found: /favicon.ico
2021-07-28 16:38:18,440 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\calculations.py changed, reloading.
2021-07-28 16:38:20,839 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 18:01:36,468 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 18:01:40,576 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 18:21:55,221 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 18:21:58,371 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 23:39:18,493 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 23:39:22,030 asyncio      DEBUG    Using selector: SelectSelector
2021-07-28 23:43:06,205 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-28 23:43:10,198 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 10:33:53,293 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 11:48:44,218 django.request WARNING  Not Found: /favicon.ico
2021-07-29 14:39:23,600 django.request WARNING  Not Found: /api/scenario/promo-simulate/
2021-07-29 15:01:32,505 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\optimizer.py changed, reloading.
2021-07-29 15:01:37,394 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 15:05:48,593 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\optimizer.py changed, reloading.
2021-07-29 15:05:50,747 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 15:06:33,618 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\optimizer.py changed, reloading.
2021-07-29 15:06:35,675 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 15:06:48,155 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\optimizer.py changed, reloading.
2021-07-29 15:06:50,079 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 15:10:24,636 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\optimizer.py changed, reloading.
2021-07-29 15:10:26,746 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 17:39:18,899 utils.app_exception_handler ERROR    null value in column "corporate_segment" violates not-null constraint
DETAIL:  Failing row contains (16, Pyaterochka, null, Orbit OTC, 0.000000000000000, null, 48).

2021-07-29 17:39:19,075 django.request ERROR    Internal Server Error: /api/scenario/save/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "corporate_segment" violates not-null constraint
DETAIL:  Failing row contains (16, Pyaterochka, null, Orbit OTC, 0.000000000000000, null, 48).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 139, in post
    pr_save.save()
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 792, in save_base
    force_update, using, update_fields,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "corporate_segment" violates not-null constraint
DETAIL:  Failing row contains (16, Pyaterochka, null, Orbit OTC, 0.000000000000000, null, 48).

2021-07-29 17:39:19,075 django.request ERROR    Internal Server Error: /api/scenario/save/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "corporate_segment" violates not-null constraint
DETAIL:  Failing row contains (16, Pyaterochka, null, Orbit OTC, 0.000000000000000, null, 48).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 139, in post
    pr_save.save()
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 792, in save_base
    force_update, using, update_fields,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "corporate_segment" violates not-null constraint
DETAIL:  Failing row contains (16, Pyaterochka, null, Orbit OTC, 0.000000000000000, null, 48).

2021-07-29 17:39:43,458 utils.app_exception_handler ERROR    PromoSave matching query does not exist.
2021-07-29 17:39:43,470 utils.app_exception_handler ERROR    PromoSave matching query does not exist.
2021-07-29 17:39:43,566 django.request ERROR    Internal Server Error: /api/scenario/list-saved-promo/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 745, in data
    ret = super().data
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 664, in to_representation
    self.child.to_representation(item) for item in iterable
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\serializers.py", line 112, in has_pricing
    return bool(obj.promo_saved.get(saved_scenario = obj).saved_pricing)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
core.models.PromoSave.DoesNotExist: PromoSave matching query does not exist.
2021-07-29 17:39:43,566 django.request ERROR    Internal Server Error: /api/scenario/list-saved-promo/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 745, in data
    ret = super().data
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 664, in to_representation
    self.child.to_representation(item) for item in iterable
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\serializers.py", line 112, in has_pricing
    return bool(obj.promo_saved.get(saved_scenario = obj).saved_pricing)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
core.models.PromoSave.DoesNotExist: PromoSave matching query does not exist.
2021-07-29 17:39:43,666 django.request ERROR    Internal Server Error: /api/scenario/list-saved-promo/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 745, in data
    ret = super().data
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 664, in to_representation
    self.child.to_representation(item) for item in iterable
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\serializers.py", line 112, in has_pricing
    return bool(obj.promo_saved.get(saved_scenario = obj).saved_pricing)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
core.models.PromoSave.DoesNotExist: PromoSave matching query does not exist.
2021-07-29 17:39:43,666 django.request ERROR    Internal Server Error: /api/scenario/list-saved-promo/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 745, in data
    ret = super().data
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 664, in to_representation
    self.child.to_representation(item) for item in iterable
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\serializers.py", line 112, in has_pricing
    return bool(obj.promo_saved.get(saved_scenario = obj).saved_pricing)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
core.models.PromoSave.DoesNotExist: PromoSave matching query does not exist.
2021-07-29 17:51:00,039 utils.app_exception_handler ERROR    null value in column "corporate_segment" violates not-null constraint
DETAIL:  Failing row contains (17, Pyaterochka, null, Orbit OTC, 0.000000000000000, null, 49).

2021-07-29 17:51:00,164 django.request ERROR    Internal Server Error: /api/scenario/save/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "corporate_segment" violates not-null constraint
DETAIL:  Failing row contains (17, Pyaterochka, null, Orbit OTC, 0.000000000000000, null, 49).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 139, in post
    pr_save.save()
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 792, in save_base
    force_update, using, update_fields,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "corporate_segment" violates not-null constraint
DETAIL:  Failing row contains (17, Pyaterochka, null, Orbit OTC, 0.000000000000000, null, 49).

2021-07-29 17:51:00,164 django.request ERROR    Internal Server Error: /api/scenario/save/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "corporate_segment" violates not-null constraint
DETAIL:  Failing row contains (17, Pyaterochka, null, Orbit OTC, 0.000000000000000, null, 49).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 139, in post
    pr_save.save()
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 792, in save_base
    force_update, using, update_fields,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "corporate_segment" violates not-null constraint
DETAIL:  Failing row contains (17, Pyaterochka, null, Orbit OTC, 0.000000000000000, null, 49).

2021-07-29 17:53:14,045 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\core\models.py changed, reloading.
2021-07-29 17:53:17,165 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 17:53:31,006 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 17:53:45,807 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 18:49:55,739 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 18:49:58,027 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 18:52:28,213 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 18:52:30,994 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 18:54:52,432 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\serializers.py changed, reloading.
2021-07-29 18:54:54,742 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 18:58:47,821 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\serializers.py changed, reloading.
2021-07-29 18:58:50,216 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 19:00:38,580 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\serializers.py changed, reloading.
2021-07-29 19:00:40,878 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 19:01:35,471 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\serializers.py changed, reloading.
2021-07-29 19:01:37,729 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 19:10:41,615 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\serializers.py changed, reloading.
2021-07-29 19:10:44,088 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 19:12:26,021 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 19:12:28,254 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 19:12:42,729 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 19:12:44,864 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 22:09:03,820 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 22:09:06,177 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 22:27:59,932 utils.app_exception_handler ERROR    Method "DELETE" not allowed.
2021-07-29 22:27:59,933 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Method "DELETE" not allowed.', code='method_not_allowed')}
2021-07-29 22:27:59,955 django.request WARNING  Method Not Allowed: /api/scenario/save/
2021-07-29 22:27:59,955 django.request WARNING  Method Not Allowed: /api/scenario/save/
2021-07-29 22:30:18,613 django.request WARNING  Not Found: /api/scenario/save/16
2021-07-29 22:30:18,613 django.request WARNING  Not Found: /api/scenario/save/16
2021-07-29 22:32:16,914 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 22:32:19,573 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 22:32:21,279 django.request WARNING  Not Found: /api/scenario/save/16
2021-07-29 22:33:20,201 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 22:33:22,471 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 22:33:26,698 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 22:33:28,863 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 22:34:21,123 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 22:34:23,435 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 22:39:14,805 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 22:39:17,332 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 22:39:29,919 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\urls.py changed, reloading.
2021-07-29 22:39:32,222 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 22:40:03,515 django.request WARNING  Not Found: /api/savedscenario/16
2021-07-29 22:42:41,792 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 22:42:44,098 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 22:42:49,694 django.request WARNING  Not Found: /api/savedscenario/16
2021-07-29 22:44:00,469 utils.app_exception_handler ERROR    Authentication credentials were not provided.
2021-07-29 22:44:00,469 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Authentication credentials were not provided.', code='not_authenticated')}
2021-07-29 22:44:00,492 django.request WARNING  Unauthorized: /api/scenario/savedscenario/16/
2021-07-29 22:44:00,492 django.request WARNING  Unauthorized: /api/scenario/savedscenario/16/
2021-07-29 22:45:31,856 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-29 22:45:34,280 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 22:56:28,005 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-29 22:56:30,321 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 22:56:39,199 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-29 22:56:41,654 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 23:01:08,668 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-29 23:01:10,924 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 23:01:17,502 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-29 23:01:19,616 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 23:01:45,692 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-29 23:01:47,898 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 23:03:42,607 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-29 23:03:44,990 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 23:06:23,282 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-29 23:06:25,549 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 23:06:37,269 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-29 23:06:39,861 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 23:07:33,475 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\optimizer.py changed, reloading.
2021-07-29 23:07:35,860 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 23:07:36,568 utils.app_exception_handler ERROR    'QuerySet' object is not a mapping
2021-07-29 23:07:36,662 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py", line 348, in post
    return Response({**serializer.data , **tpr},200)
TypeError: 'QuerySet' object is not a mapping
2021-07-29 23:07:36,662 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py", line 348, in post
    return Response({**serializer.data , **tpr},200)
TypeError: 'QuerySet' object is not a mapping
2021-07-29 23:08:31,050 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-29 23:08:33,386 asyncio      DEBUG    Using selector: SelectSelector
2021-07-29 23:15:01,482 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-29 23:15:03,866 asyncio      DEBUG    Using selector: SelectSelector
2021-07-30 10:49:29,606 asyncio      DEBUG    Using selector: SelectSelector
2021-07-30 11:13:13,786 django.request WARNING  Not Found: /api/scenario/promo-simulate/
2021-07-30 11:13:38,110 django.request WARNING  Not Found: /api/scenario/promo-simulate/
2021-07-30 12:19:23,824 django.request WARNING  Not Found: /favicon.ico
2021-07-30 19:48:25,781 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\optimizer.py changed, reloading.
2021-07-30 19:48:28,616 asyncio      DEBUG    Using selector: SelectSelector
2021-07-30 19:50:01,002 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-30 19:50:03,033 asyncio      DEBUG    Using selector: SelectSelector
2021-07-30 19:50:35,618 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-30 19:50:37,636 asyncio      DEBUG    Using selector: SelectSelector
2021-07-30 19:54:24,402 utils.app_exception_handler ERROR    When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
2021-07-30 19:54:24,457 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py", line 342, in post
    res = {"data" : serializer.data , "weekly" : tpr}
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 548, in data
    ret = super().data
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 242, in data
    raise AssertionError(msg)
AssertionError: When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
2021-07-30 19:54:24,457 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py", line 342, in post
    res = {"data" : serializer.data , "weekly" : tpr}
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 548, in data
    ret = super().data
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\serializers.py", line 242, in data
    raise AssertionError(msg)
AssertionError: When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
2021-07-30 19:55:13,750 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-30 19:55:15,709 asyncio      DEBUG    Using selector: SelectSelector
2021-07-30 22:58:18,684 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 14:36:37,065 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 14:45:34,707 utils.app_exception_handler ERROR    unsupported operand type(s) for ** or pow(): 'decimal.Decimal' and 'float'
2021-08-01 14:45:35,407 django.request ERROR    Internal Server Error: /api/scenario/promo-simulate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 760, in post
    response = self.calculate_finacial_metrics_from_request(value_dict)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 128, in calculate_finacial_metrics_from_request
    simulated_incremental_split , 'simulated',value_dict['promo_elasticity'])
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\calculations.py", line 225, in calculate_financial_mertrics
    co_investment = decimal.Decimal(data[data_values.index('co_investment')])
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\models.py", line 68, in __init__
    self.simulate_predicted_units = self.base_unit * (((1 - ((promo_depth + co_investment)/100))** promo_elasticity))
TypeError: unsupported operand type(s) for ** or pow(): 'decimal.Decimal' and 'float'
2021-08-01 14:45:35,407 django.request ERROR    Internal Server Error: /api/scenario/promo-simulate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 760, in post
    response = self.calculate_finacial_metrics_from_request(value_dict)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 128, in calculate_finacial_metrics_from_request
    simulated_incremental_split , 'simulated',value_dict['promo_elasticity'])
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\calculations.py", line 225, in calculate_financial_mertrics
    co_investment = decimal.Decimal(data[data_values.index('co_investment')])
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\models.py", line 68, in __init__
    self.simulate_predicted_units = self.base_unit * (((1 - ((promo_depth + co_investment)/100))** promo_elasticity))
TypeError: unsupported operand type(s) for ** or pow(): 'decimal.Decimal' and 'float'
2021-08-01 14:46:37,767 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\models.py changed, reloading.
2021-08-01 14:47:01,228 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 14:49:55,325 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\models.py changed, reloading.
2021-08-01 14:49:58,823 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 14:50:02,332 utils.app_exception_handler ERROR    unsupported operand type(s) for ** or pow(): 'decimal.Decimal' and 'float'
2021-08-01 14:50:02,836 django.request ERROR    Internal Server Error: /api/scenario/promo-simulate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 760, in post
    response = self.calculate_finacial_metrics_from_request(value_dict)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 128, in calculate_finacial_metrics_from_request
    simulated_incremental_split , 'simulated',value_dict['promo_elasticity'])
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\calculations.py", line 225, in calculate_financial_mertrics
    co_investment = decimal.Decimal(data[data_values.index('co_investment')])
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\models.py", line 68, in __init__
    self.simulate_predicted_units = self.base_unit * (((1 - ((promo_depth + co_investment)/100))** promo_elasticity))
TypeError: unsupported operand type(s) for ** or pow(): 'decimal.Decimal' and 'float'
2021-08-01 14:50:02,836 django.request ERROR    Internal Server Error: /api/scenario/promo-simulate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 760, in post
    response = self.calculate_finacial_metrics_from_request(value_dict)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 128, in calculate_finacial_metrics_from_request
    simulated_incremental_split , 'simulated',value_dict['promo_elasticity'])
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\calculations.py", line 225, in calculate_financial_mertrics
    co_investment = decimal.Decimal(data[data_values.index('co_investment')])
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\models.py", line 68, in __init__
    self.simulate_predicted_units = self.base_unit * (((1 - ((promo_depth + co_investment)/100))** promo_elasticity))
TypeError: unsupported operand type(s) for ** or pow(): 'decimal.Decimal' and 'float'
2021-08-01 14:51:08,636 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\models.py changed, reloading.
2021-08-01 14:51:11,847 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 14:59:08,759 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\query.py changed, reloading.
2021-08-01 14:59:12,727 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 14:59:17,668 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py changed, reloading.
2021-08-01 14:59:21,119 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 15:02:22,588 utils.app_exception_handler ERROR    Cannot resolve keyword 'neilson_sku_name' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value
2021-08-01 15:02:23,222 django.request ERROR    Internal Server Error: /api/scenario/promo-simulate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1863, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1566, in setup_joins
    names[:pivot], opts, allow_many, fail_on_missing=True,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'neilson_sku_name' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 760, in post
    response = self.calculate_finacial_metrics_from_request(value_dict)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 114, in calculate_finacial_metrics_from_request
    value_dict['product_group'] )
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\query.py", line 58, in get_list_value_from_query
    ).values_list(*const.ROI_VALUES).order_by('week')
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 868, in values_list
    clone = self._values(*_fields, **expressions)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 836, in _values
    clone.query.set_values(fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 2174, in set_values
    self.add_fields(field_names, True)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1886, in add_fields
    "Choices are: %s" % (name, ", ".join(names)))
django.core.exceptions.FieldError: Cannot resolve keyword 'neilson_sku_name' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value
2021-08-01 15:02:23,222 django.request ERROR    Internal Server Error: /api/scenario/promo-simulate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1863, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1566, in setup_joins
    names[:pivot], opts, allow_many, fail_on_missing=True,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'neilson_sku_name' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 760, in post
    response = self.calculate_finacial_metrics_from_request(value_dict)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 114, in calculate_finacial_metrics_from_request
    value_dict['product_group'] )
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\query.py", line 58, in get_list_value_from_query
    ).values_list(*const.ROI_VALUES).order_by('week')
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 868, in values_list
    clone = self._values(*_fields, **expressions)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 836, in _values
    clone.query.set_values(fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 2174, in set_values
    self.add_fields(field_names, True)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1886, in add_fields
    "Choices are: %s" % (name, ", ".join(names)))
django.core.exceptions.FieldError: Cannot resolve keyword 'neilson_sku_name' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value
2021-08-01 16:16:51,526 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py changed, reloading.
2021-08-01 16:16:55,126 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:17:02,449 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py changed, reloading.
2021-08-01 16:17:06,758 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:17:38,653 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py changed, reloading.
2021-08-01 16:17:42,728 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:17:58,203 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py changed, reloading.
2021-08-01 16:18:02,582 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:19:35,959 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py changed, reloading.
2021-08-01 16:19:39,911 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:21:30,807 utils.app_exception_handler ERROR    Cannot resolve keyword 'neilson_sku_name' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value
2021-08-01 16:21:31,737 django.request ERROR    Internal Server Error: /api/scenario/promo-simulate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1863, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1566, in setup_joins
    names[:pivot], opts, allow_many, fail_on_missing=True,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'neilson_sku_name' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 760, in post
    response = self.calculate_finacial_metrics_from_request(value_dict)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 114, in calculate_finacial_metrics_from_request
    value_dict['product_group'] )
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\query.py", line 58, in get_list_value_from_query
    ).values_list(*const.ROI_VALUES).order_by('week')
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 868, in values_list
    clone = self._values(*_fields, **expressions)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 836, in _values
    clone.query.set_values(fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 2174, in set_values
    self.add_fields(field_names, True)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1886, in add_fields
    "Choices are: %s" % (name, ", ".join(names)))
django.core.exceptions.FieldError: Cannot resolve keyword 'neilson_sku_name' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value
2021-08-01 16:21:31,737 django.request ERROR    Internal Server Error: /api/scenario/promo-simulate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1863, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1566, in setup_joins
    names[:pivot], opts, allow_many, fail_on_missing=True,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'neilson_sku_name' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 760, in post
    response = self.calculate_finacial_metrics_from_request(value_dict)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 114, in calculate_finacial_metrics_from_request
    value_dict['product_group'] )
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\query.py", line 58, in get_list_value_from_query
    ).values_list(*const.ROI_VALUES).order_by('week')
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 868, in values_list
    clone = self._values(*_fields, **expressions)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 836, in _values
    clone.query.set_values(fields)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 2174, in set_values
    self.add_fields(field_names, True)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1886, in add_fields
    "Choices are: %s" % (name, ", ".join(names)))
django.core.exceptions.FieldError: Cannot resolve keyword 'neilson_sku_name' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value
2021-08-01 16:22:43,916 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\query.py changed, reloading.
2021-08-01 16:22:48,414 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:23:07,113 utils.app_exception_handler ERROR    Cannot resolve keyword 'week' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value
2021-08-01 16:23:07,445 django.request ERROR    Internal Server Error: /api/scenario/promo-simulate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 760, in post
    response = self.calculate_finacial_metrics_from_request(value_dict)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 114, in calculate_finacial_metrics_from_request
    value_dict['product_group'] )
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\query.py", line 58, in get_list_value_from_query
    ).values_list('coefficient_old' , 'coefficient_new').order_by('week')
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 1134, in order_by
    obj.query.add_ordering(*field_names)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1919, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'week' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value
2021-08-01 16:23:07,445 django.request ERROR    Internal Server Error: /api/scenario/promo-simulate/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 760, in post
    response = self.calculate_finacial_metrics_from_request(value_dict)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 114, in calculate_finacial_metrics_from_request
    value_dict['product_group'] )
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\query.py", line 58, in get_list_value_from_query
    ).values_list('coefficient_old' , 'coefficient_new').order_by('week')
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\query.py", line 1134, in order_by
    obj.query.add_ordering(*field_names)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1919, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\db\models\sql\query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'week' into field. Choices are: coefficient_new, coefficient_old, id, model_meta, model_meta_id, value
2021-08-01 16:23:40,661 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\query.py changed, reloading.
2021-08-01 16:23:43,981 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:29:22,980 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\query.py changed, reloading.
2021-08-01 16:29:26,745 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:38:01,849 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\calculations.py changed, reloading.
2021-08-01 16:38:06,018 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:43:55,782 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\calculations.py changed, reloading.
2021-08-01 16:44:00,248 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:46:02,963 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\calculations.py changed, reloading.
2021-08-01 16:46:07,212 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:48:26,669 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py changed, reloading.
2021-08-01 16:48:31,388 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 16:49:36,300 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py changed, reloading.
2021-08-01 16:49:40,966 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 23:00:16,928 utils.app_exception_handler ERROR    No SavedScenario matches the given query.
2021-08-01 23:00:16,928 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Not found.', code='not_found')}
2021-08-01 23:00:17,071 django.request WARNING  Not Found: /api/scenario/savedscenario/35/
2021-08-01 23:00:17,071 django.request WARNING  Not Found: /api/scenario/savedscenario/35/
2021-08-01 23:04:53,130 utils.app_exception_handler ERROR    too many values to unpack (expected 3)
2021-08-01 23:04:53,427 django.request ERROR    Internal Server Error: /api/scenario/list-saved-promo/42/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 558, in retrieve
    return Response( self.calculate_finacial_metrics_pricing_promo(weeks,pricing_week ),
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 214, in calculate_finacial_metrics_pricing_promo
    product_group )
ValueError: too many values to unpack (expected 3)
2021-08-01 23:04:53,427 django.request ERROR    Internal Server Error: /api/scenario/list-saved-promo/42/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 558, in retrieve
    return Response( self.calculate_finacial_metrics_pricing_promo(weeks,pricing_week ),
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 214, in calculate_finacial_metrics_pricing_promo
    product_group )
ValueError: too many values to unpack (expected 3)
2021-08-01 23:06:33,818 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py changed, reloading.
2021-08-01 23:06:39,892 asyncio      DEBUG    Using selector: SelectSelector
2021-08-01 23:08:19,133 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\calculations.py changed, reloading.
2021-08-01 23:08:23,865 asyncio      DEBUG    Using selector: SelectSelector
2021-08-02 00:01:39,869 utils.app_exception_handler ERROR    too many values to unpack (expected 3)
2021-08-02 00:01:40,082 django.request ERROR    Internal Server Error: /api/scenario/list-saved-promo/47/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 563, in retrieve
    return Response( self.calculate_finacial_metrics(weeks),
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 166, in calculate_finacial_metrics
    product_group )
ValueError: too many values to unpack (expected 3)
2021-08-02 00:01:40,082 django.request ERROR    Internal Server Error: /api/scenario/list-saved-promo/47/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 563, in retrieve
    return Response( self.calculate_finacial_metrics(weeks),
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py", line 166, in calculate_finacial_metrics
    product_group )
ValueError: too many values to unpack (expected 3)
2021-08-02 00:04:02,243 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\mixins.py changed, reloading.
2021-08-02 00:04:05,658 asyncio      DEBUG    Using selector: SelectSelector
2021-08-02 09:58:55,021 asyncio      DEBUG    Using selector: SelectSelector
