2021-08-17 11:29:21,613 django.utils.autoreload INFO     D:\MARS-RUSSIA\price-simulator-backend\app\settings.py changed, reloading.
2021-08-17 11:29:23,998 asyncio      DEBUG    Using proactor: IocpProactor
2021-08-17 11:49:20,986 utils.app_exception_handler ERROR    'NoneType' object is not subscriptable
2021-08-17 11:49:21,132 django.request ERROR    Internal Server Error: /api/optimiser/optimizer-download/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 36, in post
    excel.download_excel_optimizer(
  File "D:\MARS-RUSSIA\price-simulator-backend\utils\excel.py", line 474, in download_excel_optimizer
    simulated_weekly = data['financial_metrics']['simulated']['weekly']
TypeError: 'NoneType' object is not subscriptable
2021-08-17 11:49:21,132 django.request ERROR    Internal Server Error: /api/optimiser/optimizer-download/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 36, in post
    excel.download_excel_optimizer(
  File "D:\MARS-RUSSIA\price-simulator-backend\utils\excel.py", line 474, in download_excel_optimizer
    simulated_weekly = data['financial_metrics']['simulated']['weekly']
TypeError: 'NoneType' object is not subscriptable
2021-08-17 11:50:59,134 utils.app_exception_handler ERROR    column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:50:59,639 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2168, in process
    pr.get_list_from_db(constraints['account_name'],
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\process.py", line 51, in get_list_from_db
    model_data_list = [list(i) for i in model_data]
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 287, in __iter__
    self._fetch_all()
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 142, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:50:59,639 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2168, in process
    pr.get_list_from_db(constraints['account_name'],
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\process.py", line 51, in get_list_from_db
    model_data_list = [list(i) for i in model_data]
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 287, in __iter__
    self._fetch_all()
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 142, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:51:25,090 utils.app_exception_handler ERROR    column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:51:25,484 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2168, in process
    pr.get_list_from_db(constraints['account_name'],
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\process.py", line 51, in get_list_from_db
    model_data_list = [list(i) for i in model_data]
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 287, in __iter__
    self._fetch_all()
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 142, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:51:25,484 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2168, in process
    pr.get_list_from_db(constraints['account_name'],
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\process.py", line 51, in get_list_from_db
    model_data_list = [list(i) for i in model_data]
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 287, in __iter__
    self._fetch_all()
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 142, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:54:57,352 utils.app_exception_handler ERROR    column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:54:57,767 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2168, in process
    pr.get_list_from_db(constraints['account_name'],
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\process.py", line 51, in get_list_from_db
    model_data_list = [list(i) for i in model_data]
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 287, in __iter__
    self._fetch_all()
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 142, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:54:57,767 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2168, in process
    pr.get_list_from_db(constraints['account_name'],
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\process.py", line 51, in get_list_from_db
    model_data_list = [list(i) for i in model_data]
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 287, in __iter__
    self._fetch_all()
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 142, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:55:30,090 utils.app_exception_handler ERROR    column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:55:30,559 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2168, in process
    pr.get_list_from_db(constraints['account_name'],
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\process.py", line 51, in get_list_from_db
    model_data_list = [list(i) for i in model_data]
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 287, in __iter__
    self._fetch_all()
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 142, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:55:30,559 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2168, in process
    pr.get_list_from_db(constraints['account_name'],
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\process.py", line 51, in get_list_from_db
    model_data_list = [list(i) for i in model_data]
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 287, in __iter__
    self._fetch_all()
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 142, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:55:38,071 utils.app_exception_handler ERROR    column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:55:38,442 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2168, in process
    pr.get_list_from_db(constraints['account_name'],
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\process.py", line 51, in get_list_from_db
    model_data_list = [list(i) for i in model_data]
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 287, in __iter__
    self._fetch_all()
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 142, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:55:38,442 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2168, in process
    pr.get_list_from_db(constraints['account_name'],
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\process.py", line 51, in get_list_from_db
    model_data_list = [list(i) for i in model_data]
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 287, in __iter__
    self._fetch_all()
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\query.py", line 142, in __iter__
    return compiler.results_iter(tuple_expected=True, chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1108, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 133, in _record
    return method(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column model_data.death_rate does not exist
LINE 1: ..._grams", "model_data"."weighted_weight_in_grams", "model_dat...
                                                             ^

2021-08-17 11:56:58,091 asyncio      DEBUG    Using proactor: IocpProactor
2021-08-17 11:57:12,428 asyncio      DEBUG    Using proactor: IocpProactor
2021-08-17 11:57:27,885 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\2fa92d38bf684dd99cb4cd21f1800018-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\2fa92d38bf684dd99cb4cd21f1800018-pulp.sol 
2021-08-17 11:57:28,467 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\9459da0760aa4dad95f01b47aa5769e0-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\9459da0760aa4dad95f01b47aa5769e0-pulp.sol 
2021-08-17 11:58:08,536 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\f625189733264d15bf201a4b6359b50e-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\f625189733264d15bf201a4b6359b50e-pulp.sol 
2021-08-17 11:58:09,018 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\236fe93882a84b8dbea98b2abd850219-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\236fe93882a84b8dbea98b2abd850219-pulp.sol 
2021-08-17 12:01:19,329 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\b78bd7af646a4702b501f0b0203cefef-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\b78bd7af646a4702b501f0b0203cefef-pulp.sol 
2021-08-17 12:01:19,608 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\5f73acbeb3cb4413852f7b5e7839d0ff-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\5f73acbeb3cb4413852f7b5e7839d0ff-pulp.sol 
2021-08-17 12:01:27,648 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\5c4f0c6ac56a4abe955b8b93d558cc3e-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\5c4f0c6ac56a4abe955b8b93d558cc3e-pulp.sol 
2021-08-17 12:01:27,980 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\b3d100aa8a204c04b89865312edeb8b4-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\b3d100aa8a204c04b89865312edeb8b4-pulp.sol 
2021-08-17 12:01:34,064 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\30598c6cf2114d16b83d4ce801016d7b-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\30598c6cf2114d16b83d4ce801016d7b-pulp.sol 
2021-08-17 12:01:34,412 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\b8402c585f4f49cfae8980fc3ebdee85-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\b8402c585f4f49cfae8980fc3ebdee85-pulp.sol 
2021-08-17 12:12:16,080 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\8904f74c80834e70902c6bb7c28109ce-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\8904f74c80834e70902c6bb7c28109ce-pulp.sol 
2021-08-17 12:12:16,559 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\1c17c3ae294c4ff3b5022460ed946e9c-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\1c17c3ae294c4ff3b5022460ed946e9c-pulp.sol 
2021-08-17 12:16:16,051 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\b431c036b8c8443d91aef07ac20b8ae3-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\b431c036b8c8443d91aef07ac20b8ae3-pulp.sol 
2021-08-17 12:16:16,491 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\da0f26dca2954ad6bf0c625092818082-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\da0f26dca2954ad6bf0c625092818082-pulp.sol 
2021-08-17 12:20:01,785 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\f19d7d755fa44463981eadb1b8d7f1f3-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\f19d7d755fa44463981eadb1b8d7f1f3-pulp.sol 
2021-08-17 12:20:02,299 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\ce6eb63ffaed40b5a1dcf2521fb5cb63-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\ce6eb63ffaed40b5a1dcf2521fb5cb63-pulp.sol 
2021-08-17 13:16:48,880 utils.app_exception_handler ERROR    local variable 'Optimal_data' referenced before assignment
2021-08-17 13:16:49,640 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2926, in process
    opt_base[value] = Optimal_data[value]
UnboundLocalError: local variable 'Optimal_data' referenced before assignment
2021-08-17 13:16:49,640 django.request ERROR    Internal Server Error: /api/optimiser/calculate/
Traceback (most recent call last):
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\views.py", line 418, in post
    return Response(optimizer.process(dict(ser.validated_data)) , 200)
  File "D:\MARS-RUSSIA\price-simulator-backend\optimiser\optimizer.py", line 2926, in process
    opt_base[value] = Optimal_data[value]
UnboundLocalError: local variable 'Optimal_data' referenced before assignment
2021-08-17 13:39:11,569 pulp.apis.core DEBUG    D:\MARS-RUSSIA\price-simulator-backend\.venv\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\YUVANE~1.DHA\AppData\Local\Temp\e26eb9ad82924c488dbd0f7bf18c92df-pulp.mps max branch printingOptions all solution C:\Users\YUVANE~1.DHA\AppData\Local\Temp\e26eb9ad82924c488dbd0f7bf18c92df-pulp.sol 
2021-08-17 14:41:09,981 utils.app_exception_handler ERROR    Invalid token.
2021-08-17 14:41:09,982 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Invalid token.', code='authentication_failed')}
2021-08-17 14:41:10,025 django.request WARNING  Unauthorized: /api/scenario/promo-simulate-test/
2021-08-17 14:41:10,025 django.request WARNING  Unauthorized: /api/scenario/promo-simulate-test/
2021-08-17 14:41:27,993 utils.app_exception_handler ERROR    Invalid token.
2021-08-17 14:41:27,994 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Invalid token.', code='authentication_failed')}
2021-08-17 14:41:28,024 django.request WARNING  Unauthorized: /api/scenario/promo-simulate-test/
2021-08-17 14:41:28,024 django.request WARNING  Unauthorized: /api/scenario/promo-simulate-test/
2021-08-17 14:44:41,396 utils.app_exception_handler ERROR    Invalid token.
2021-08-17 14:44:41,396 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Invalid token.', code='authentication_failed')}
2021-08-17 14:44:41,424 django.request WARNING  Unauthorized: /api/scenario/promo-simulate-test/
2021-08-17 14:44:41,424 django.request WARNING  Unauthorized: /api/scenario/promo-simulate-test/
2021-08-17 14:44:48,748 utils.app_exception_handler ERROR    Invalid token.
2021-08-17 14:44:48,749 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Invalid token.', code='authentication_failed')}
2021-08-17 14:44:48,781 django.request WARNING  Unauthorized: /api/user/logout/
2021-08-17 14:44:48,781 django.request WARNING  Unauthorized: /api/user/logout/
2021-08-17 14:45:03,551 django.request WARNING  Not Found: /favicon.ico
2021-08-17 14:45:03,551 django.request WARNING  Not Found: /favicon.ico
2021-08-17 14:45:25,071 utils.app_exception_handler ERROR    Invalid token.
2021-08-17 14:45:25,071 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Invalid token.', code='authentication_failed')}
2021-08-17 14:45:25,102 django.request WARNING  Unauthorized: /api/scenario/promo-simulate-test/
2021-08-17 14:45:25,102 django.request WARNING  Unauthorized: /api/scenario/promo-simulate-test/
2021-08-17 16:42:09,291 django.utils.autoreload INFO     D:\MARS-RUSSIA\price-simulator-backend\app\settings.py changed, reloading.
2021-08-17 16:42:11,832 asyncio      DEBUG    Using proactor: IocpProactor
2021-08-17 16:46:28,487 asyncio      DEBUG    Using proactor: IocpProactor
2021-08-17 16:48:11,040 django.utils.autoreload INFO     D:\MARS-RUSSIA\price-simulator-backend\app\settings.py changed, reloading.
2021-08-17 16:48:13,444 asyncio      DEBUG    Using proactor: IocpProactor
