2021-07-12 16:13:08,774 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 16:13:13,058 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 16:13:19,234 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 18:04:00,478 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 18:10:14,450 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 18:13:39,707 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 18:15:03,021 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 18:26:47,698 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 18:26:57,073 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-12 18:27:06,288 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-12 19:27:42,501 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 19:28:05,794 utils.app_exception_handler ERROR    'cross_elasticity'
2021-07-12 19:28:11,597 django.request ERROR    Internal Server Error: /api/scenario/scenario-metrics/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'cross_elasticity'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 445, in list
    data , coeff = uc.list_to_frame_many(coeff_list , data_list)
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 519, in list_to_frame_many
    (coeff_dt['PPG'] == row['PPG'])])
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 340, in main
    train_data['Units']=predict_sales(model_coef,train_data)
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 23, in predict_sales
    data[i] =  data[i].astype(float)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'cross_elasticity'
2021-07-12 19:28:11,597 django.request ERROR    Internal Server Error: /api/scenario/scenario-metrics/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'cross_elasticity'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 445, in list
    data , coeff = uc.list_to_frame_many(coeff_list , data_list)
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 519, in list_to_frame_many
    (coeff_dt['PPG'] == row['PPG'])])
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 340, in main
    train_data['Units']=predict_sales(model_coef,train_data)
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 23, in predict_sales
    data[i] =  data[i].astype(float)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'cross_elasticity'
2021-07-12 19:29:17,684 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 19:30:22,616 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 19:46:20,152 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 19:46:28,772 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-12 19:47:18,253 utils.app_exception_handler ERROR    Can only merge Series or DataFrame objects, a <class 'list'> was passed
2021-07-12 19:47:26,639 django.request ERROR    Internal Server Error: /api/scenario/scenario-metrics/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 445, in list
    result_dt = uc.list_to_frame_many(coeff_list , data_list)
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 549, in list_to_frame_many
    result_dt = pd.merge(data,coeff,how="inner" ,left_on = ["Account Name" , "PPG"] , right_on = ["Account Name" , "PPG"])
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 87, in merge
    validate=validate,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 598, in __init__
    _left = _validate_operand(left)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 2149, in _validate_operand
    f"Can only merge Series or DataFrame objects, a {type(obj)} was passed"
TypeError: Can only merge Series or DataFrame objects, a <class 'list'> was passed
2021-07-12 19:47:26,639 django.request ERROR    Internal Server Error: /api/scenario/scenario-metrics/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 445, in list
    result_dt = uc.list_to_frame_many(coeff_list , data_list)
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 549, in list_to_frame_many
    result_dt = pd.merge(data,coeff,how="inner" ,left_on = ["Account Name" , "PPG"] , right_on = ["Account Name" , "PPG"])
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 87, in merge
    validate=validate,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 598, in __init__
    _left = _validate_operand(left)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 2149, in _validate_operand
    f"Can only merge Series or DataFrame objects, a {type(obj)} was passed"
TypeError: Can only merge Series or DataFrame objects, a <class 'list'> was passed
2021-07-12 19:49:48,133 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 19:52:36,890 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 20:24:04,345 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-12 20:24:15,729 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-12 20:24:25,113 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-12 20:25:48,503 utils.app_exception_handler ERROR    Can only merge Series or DataFrame objects, a <class 'list'> was passed
2021-07-12 20:25:48,504 utils.app_exception_handler ERROR    Can only merge Series or DataFrame objects, a <class 'list'> was passed
2021-07-12 20:25:58,978 django.request ERROR    Internal Server Error: /api/scenario/scenario-metrics/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 445, in list
    result_dt = uc.list_to_frame_many(coeff_list , data_list , roi_list)
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 557, in list_to_frame_many
    result_dt = pd.merge(result_dt,roi,how="inner" ,left_on = ["Account Name" , "PPG"] , right_on = ["Account Name" , "PPG"])
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 87, in merge
    validate=validate,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 599, in __init__
    _right = _validate_operand(right)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 2149, in _validate_operand
    f"Can only merge Series or DataFrame objects, a {type(obj)} was passed"
TypeError: Can only merge Series or DataFrame objects, a <class 'list'> was passed
2021-07-12 20:25:58,978 django.request ERROR    Internal Server Error: /api/scenario/scenario-metrics/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 445, in list
    result_dt = uc.list_to_frame_many(coeff_list , data_list , roi_list)
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 557, in list_to_frame_many
    result_dt = pd.merge(result_dt,roi,how="inner" ,left_on = ["Account Name" , "PPG"] , right_on = ["Account Name" , "PPG"])
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 87, in merge
    validate=validate,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 599, in __init__
    _right = _validate_operand(right)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 2149, in _validate_operand
    f"Can only merge Series or DataFrame objects, a {type(obj)} was passed"
TypeError: Can only merge Series or DataFrame objects, a <class 'list'> was passed
2021-07-12 20:25:58,978 django.request ERROR    Internal Server Error: /api/scenario/scenario-metrics/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 445, in list
    result_dt = uc.list_to_frame_many(coeff_list , data_list , roi_list)
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 557, in list_to_frame_many
    result_dt = pd.merge(result_dt,roi,how="inner" ,left_on = ["Account Name" , "PPG"] , right_on = ["Account Name" , "PPG"])
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 87, in merge
    validate=validate,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 599, in __init__
    _right = _validate_operand(right)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 2149, in _validate_operand
    f"Can only merge Series or DataFrame objects, a {type(obj)} was passed"
TypeError: Can only merge Series or DataFrame objects, a <class 'list'> was passed
2021-07-12 20:25:58,978 django.request ERROR    Internal Server Error: /api/scenario/scenario-metrics/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 445, in list
    result_dt = uc.list_to_frame_many(coeff_list , data_list , roi_list)
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py", line 557, in list_to_frame_many
    result_dt = pd.merge(result_dt,roi,how="inner" ,left_on = ["Account Name" , "PPG"] , right_on = ["Account Name" , "PPG"])
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 87, in merge
    validate=validate,
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 599, in __init__
    _right = _validate_operand(right)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pandas\core\reshape\merge.py", line 2149, in _validate_operand
    f"Can only merge Series or DataFrame objects, a {type(obj)} was passed"
TypeError: Can only merge Series or DataFrame objects, a <class 'list'> was passed
2021-07-12 20:26:43,942 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 20:30:46,983 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-12 20:40:02,224 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-13 15:30:52,442 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-13 15:43:34,925 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-13 15:45:52,327 django.request WARNING  Not Found: /favicon.ico
2021-07-13 15:51:32,287 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-13 15:53:33,890 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\units_calculation.py changed, reloading.
2021-07-13 15:57:25,474 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-13 17:15:24,480 django.request WARNING  Not Found: /api/optimiser/calcu
2021-07-13 17:15:29,961 utils.app_exception_handler ERROR    Method "GET" not allowed.
2021-07-13 17:15:29,962 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Method "GET" not allowed.', code='method_not_allowed')}
2021-07-13 17:15:30,025 django.request WARNING  Method Not Allowed: /api/optimiser/optimizer-download/
2021-07-13 17:15:30,025 django.request WARNING  Method Not Allowed: /api/optimiser/optimizer-download/
2021-07-13 17:20:09,476 root         INFO     Main Funtion Begin
2021-07-13 17:20:09,686 root         INFO     Calculate Predict Sales
2021-07-13 17:20:09,709 root         INFO     Promo Wave/Slot Calculation
2021-07-13 17:20:09,873 root         INFO     Fetching TE Dict
2021-07-13 17:20:09,888 root         INFO     Get required base
2021-07-13 17:20:09,915 root         INFO     Calculate Predict Sales
2021-07-13 17:20:09,955 root         INFO     Calculate Predict Sales
2021-07-13 17:20:10,004 root         INFO     Optimizer function
2021-07-13 17:20:10,058 pulp.apis.core DEBUG    D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\341e77d9fb0c4b938a904f487f23f39d-pulp.mps max branch printingOptions all solution C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\341e77d9fb0c4b938a904f487f23f39d-pulp.sol 
2021-07-13 17:20:38,872 root         INFO     Optimizer function
2021-07-13 17:20:38,933 pulp.apis.core DEBUG    D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\1a213f44859f4b33b2141391169933df-pulp.mps max branch printingOptions all solution C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\1a213f44859f4b33b2141391169933df-pulp.sol 
2021-07-13 17:21:12,343 root         INFO     Optimizer function
2021-07-13 17:21:12,405 pulp.apis.core DEBUG    D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\ac067ec293544e7d8af70b31cff3a394-pulp.mps max branch printingOptions all solution C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\ac067ec293544e7d8af70b31cff3a394-pulp.sol 
2021-07-13 17:21:42,702 root         INFO     Optimizer function
2021-07-13 17:21:42,757 pulp.apis.core DEBUG    D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\6ddb2ea562d64e1993bd460e2d118667-pulp.mps max branch printingOptions all solution C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\6ddb2ea562d64e1993bd460e2d118667-pulp.sol 
2021-07-13 17:22:36,338 root         INFO     Optimizer function
2021-07-13 17:22:36,417 pulp.apis.core DEBUG    D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\b84c5f20c28a42d48a5ae87441bfef57-pulp.mps max branch printingOptions all solution C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\b84c5f20c28a42d48a5ae87441bfef57-pulp.sol 
2021-07-13 17:23:10,104 root         INFO     Main Funtion Begin
2021-07-13 17:23:10,304 root         INFO     Calculate Predict Sales
2021-07-13 17:23:10,328 root         INFO     Promo Wave/Slot Calculation
2021-07-13 17:23:10,501 root         INFO     Fetching TE Dict
2021-07-13 17:23:10,511 root         INFO     Get required base
2021-07-13 17:23:10,520 root         INFO     Calculate Predict Sales
2021-07-13 17:23:10,564 root         INFO     Calculate Predict Sales
2021-07-13 17:23:10,588 root         INFO     Optimizer function
2021-07-13 17:23:10,643 pulp.apis.core DEBUG    D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\e45d3d0b03af491f990f578f32ef0a65-pulp.mps max branch printingOptions all solution C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\e45d3d0b03af491f990f578f32ef0a65-pulp.sol 
2021-07-13 17:26:17,468 root         INFO     Main Funtion Begin
2021-07-13 17:26:17,727 root         INFO     Calculate Predict Sales
2021-07-13 17:26:17,759 root         INFO     Promo Wave/Slot Calculation
2021-07-13 17:26:17,951 root         INFO     Fetching TE Dict
2021-07-13 17:26:17,965 root         INFO     Get required base
2021-07-13 17:26:18,008 root         INFO     Calculate Predict Sales
2021-07-13 17:26:18,095 root         INFO     Calculate Predict Sales
2021-07-13 17:26:18,128 root         INFO     Calculate Predict Sales
2021-07-13 17:26:18,155 root         INFO     Calculate Predict Sales
2021-07-13 17:26:18,180 root         INFO     Calculate Predict Sales
2021-07-13 17:26:18,212 root         INFO     Optimizer function
2021-07-13 17:26:18,378 pulp.apis.core DEBUG    D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\a4562616c05445e6b3c9a1cb4b9143b2-pulp.mps branch printingOptions all solution C:\Users\ARAVIN~1.MAT\AppData\Local\Temp\a4562616c05445e6b3c9a1cb4b9143b2-pulp.sol 
2021-07-13 17:26:18,929 root         INFO     Optimal Summary Function
2021-07-13 17:26:18,934 root         INFO     Calculate Predict Sales
2021-07-13 17:26:18,965 root         INFO     Get optimal base comparison
2021-07-13 17:26:18,966 root         INFO     Promo Wave/Slot Calculation
2021-07-13 17:26:18,992 root         INFO     Base variable change as required
2021-07-13 17:26:19,254 root         INFO     Promo Wave/Slot Calculation
2021-07-13 17:26:19,265 root         INFO     Base variable change as required
2021-07-13 17:26:19,569 root         INFO     Get calendar summary data
2021-07-13 17:26:19,739 root         INFO     Main Funtion Ends
2021-07-13 18:05:37,384 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-13 18:06:35,308 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-13 19:21:54,488 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-13 19:25:25,538 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-13 19:27:21,704 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 19:27:52,625 utils.app_exception_handler ERROR    'str' object has no attribute 'strftime'
2021-07-13 19:27:53,158 django.request ERROR    Internal Server Error: /api/scenario/promo-download/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 710, in post
    excel.download_excel_promo_compare('response'),
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py", line 297, in download_excel_promo_compare
    week[k].strftime("%b %d %Y") if k =='date' else week[k],
AttributeError: 'str' object has no attribute 'strftime'
2021-07-13 19:27:53,158 django.request ERROR    Internal Server Error: /api/scenario/promo-download/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 710, in post
    excel.download_excel_promo_compare('response'),
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py", line 297, in download_excel_promo_compare
    week[k].strftime("%b %d %Y") if k =='date' else week[k],
AttributeError: 'str' object has no attribute 'strftime'
2021-07-13 19:29:04,465 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 19:35:50,783 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 19:37:40,259 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 19:38:50,924 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 19:40:15,403 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 19:41:23,940 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 19:41:43,617 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 19:43:40,331 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-13 20:32:50,144 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py changed, reloading.
2021-07-13 20:36:13,057 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\util.py changed, reloading.
2021-07-13 20:36:42,960 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\util.py changed, reloading.
2021-07-13 20:36:57,923 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\util.py changed, reloading.
2021-07-13 20:38:34,737 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\util.py changed, reloading.
2021-07-13 20:40:32,618 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 20:41:08,250 utils.app_exception_handler ERROR    local variable 'final' referenced before assignment
2021-07-13 20:41:08,730 django.request ERROR    Internal Server Error: /api/scenario/promo-download/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 710, in post
    excel.download_excel_promo_compare('response'),
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py", line 299, in download_excel_promo_compare
    week[k] if k =='date' else util.format_value(week[k]),
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\util.py", line 29, in format_value
    return "{} {}".format("{:.2f}".format(final),curr)
UnboundLocalError: local variable 'final' referenced before assignment
2021-07-13 20:41:08,730 django.request ERROR    Internal Server Error: /api/scenario/promo-download/
Traceback (most recent call last):
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\projects\MARSBACKEND\price-simulator-backend\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\projects\MARSBACKEND\price-simulator-backend\scenario_planner\views.py", line 710, in post
    excel.download_excel_promo_compare('response'),
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py", line 299, in download_excel_promo_compare
    week[k] if k =='date' else util.format_value(week[k]),
  File "D:\projects\MARSBACKEND\price-simulator-backend\utils\util.py", line 29, in format_value
    return "{} {}".format("{:.2f}".format(final),curr)
UnboundLocalError: local variable 'final' referenced before assignment
2021-07-13 20:41:42,705 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\util.py changed, reloading.
2021-07-13 20:43:57,004 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\util.py changed, reloading.
2021-07-13 20:50:00,812 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 20:51:43,292 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 20:52:30,316 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-13 21:00:46,800 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-14 10:53:04,585 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-14 11:11:45,411 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-14 11:20:16,753 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\utils\excel.py changed, reloading.
2021-07-14 11:20:48,757 django.request WARNING  Not Found: /favicon.ico
2021-07-14 13:02:27,727 django.request WARNING  Not Found: /favicon.ico
2021-07-14 19:26:56,364 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\serializers.py changed, reloading.
2021-07-14 19:27:43,570 django.utils.autoreload INFO     D:\projects\MARSBACKEND\price-simulator-backend\optimiser\views.py changed, reloading.
2021-07-14 19:30:47,034 utils.app_exception_handler ERROR    Authentication credentials were not provided.
2021-07-14 19:30:47,036 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Authentication credentials were not provided.', code='not_authenticated')}
2021-07-14 19:30:47,192 django.request WARNING  Unauthorized: /api/optimiser/calculate/
2021-07-14 19:30:47,192 django.request WARNING  Unauthorized: /api/optimiser/calculate/
2021-07-14 19:35:18,948 utils.app_exception_handler ERROR    Authentication credentials were not provided.
2021-07-14 19:35:18,948 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Authentication credentials were not provided.', code='not_authenticated')}
2021-07-14 19:35:19,022 django.request WARNING  Unauthorized: /api/optimiser/calculate/
2021-07-14 19:35:19,022 django.request WARNING  Unauthorized: /api/optimiser/calculate/
2021-07-14 19:40:31,431 utils.app_exception_handler ERROR    Authentication credentials were not provided.
2021-07-14 19:40:31,431 utils.app_exception_handler ERROR    {'detail': ErrorDetail(string='Authentication credentials were not provided.', code='not_authenticated')}
2021-07-14 19:40:31,519 django.request WARNING  Unauthorized: /api/optimiser/calculate/
2021-07-14 19:40:31,519 django.request WARNING  Unauthorized: /api/optimiser/calculate/
